IGC-The-Binding-Of-Issac/The-Binding-Of-Issac

Assets/Prefabs/Player.prefab
Assets/Script/ManagerScript/PlayerManager.cs
Assets/Script/StageScript/Object/FirePlace.cs
Assets/Script/StageScript/Object/Spikes.cs
ProjectSettings/TagManager.asset

PlayerManager  GetDamage() 추가
가시, 모닥불 충돌 작성

가시, 모닥불,플레이어 매니저 업데이트

---

Assets/Enemy_tmp 1.prefab
Assets/Enemy_tmp 1.prefab.meta
Assets/Enemy_tmp 2.prefab
Assets/Enemy_tmp 2.prefab.meta
Assets/Item/Bomb/BombScript/Bomb.cs
Assets/Item/ItemManager.cs
Assets/Scenes/02_Game.unity
Assets/Script/StageScript/Door.cs
Assets/Script/StageScript/EnemyGenerate.cs
Assets/Script/StageScript/EnemyGenerate.cs.meta
Assets/Script/StageScript/RoomGenerate.cs

몬스터 랜덤생성 ., 문 열쇠사용

---

Assets/Item/ItemManager.cs
Assets/Script/ManagerScript/GameManager.cs

ItemManager
아이템별로 Header 달아줌.
패시브아이템 보유현황 bool형 배열로 변경.
액티브아이템,장신구아이템 받아줄 변수 선언.
GameManager 사망시, 클리어시 함수틀 작성해둠.

ItemManager , GameManager 수정

---

Assets/Enemy/PrePab/AttackFly.prefab
Assets/Enemy/PrePab/Hive.prefab
Assets/Enemy/PrePab/Hive.prefab.meta
Assets/Enemy/PrePab/Moter.prefab
Assets/Enemy/Script/Enemy.cs
Assets/Enemy/Script/Issac/Hive.cs
Assets/Enemy/Script/Spider/Spider.cs
Assets/Enemy/Script/Top/Top_Fly.cs
Assets/Enemy/Script/Top/Top_Spider.cs

1008 : Enemy : Hive 구현

---

Assets/Enemy/Animation/Spider/Tride.controller
Assets/Enemy/PrePab/Issac/Maw.prefab
Assets/Enemy/Script/Spider/Tride.cs
Assets/Scenes/02_Game.unity

Tride 유한상태머신으로 구현중,
Move스크립트에 state 변환 코드 넣어줘야함
(총알 발사하듯이 시간으로 state변환 하면 될듯?)

1011 enemy add

---

Assets/Animation/player/Tear/Tear.controller
Assets/Script/ManagerScript/EnemyLayerManager.cs
Assets/Script/ManagerScript/EnemyLayerManager.cs.meta

y값에 따라 Enemy의 레이어 값이 바뀌도록 코드를 추가함

Enemy 레이어 조정

---

Assets/Enemy/Animation/Spider/Spider.controller
Assets/Enemy/Animation/Spider/Spider_Idle.anim
Assets/Enemy/Animation/Spider/Top_Spider_ide.anim
Assets/Enemy/Animation/Spider/Tride.controller
Assets/Enemy/Animation/Spider/Tride_jump.anim
Assets/Enemy/PrePab/Spider/Tride.prefab
Assets/Enemy/Script/Fly/Footer.cs
Assets/Enemy/Script/Spider/Spider.cs
Assets/Enemy/Script/Spider/Tride.cs
Assets/Scenes/02_Game.unity

: Tride점프를 어떻게 구현 해야 할지 모르겠다
플레이어와 Tride 거리가 가까울때, 애니메이션이 짧게 실행되고
플레이어와 Tride 거리가 멀 때는 애니메이션이 길게 실행되게 하고싶

1017_Enemy

---

Assets/Enemy/Animation/Spider/Tride.controller
Assets/Enemy/Script/Spider/Tride.cs

1018_Enemy_Tride

---

Assets/Enemy/Animation/Spider/Spider.controller
Assets/Enemy/Animation/Spider/Spider_Idle.anim
Assets/Enemy/Animation/Spider/Spider_Idle.anim.meta
Assets/Enemy/Animation/Spider/Spider_move.anim
Assets/Enemy/Animation/Spider/Spider_move.anim.meta
Assets/Enemy/Animation/Spider/Top_Spider_ide.anim
Assets/Enemy/Animation/Spider/Top_Spider_ide.anim.meta
Assets/Enemy/PrePab/Fly/AttackFly.prefab
Assets/Enemy/PrePab/Fly/Moter.prefab
Assets/Enemy/PrePab/Fly/Pooter.prefab
Assets/Enemy/PrePab/Issac/Maw.prefab
Assets/Enemy/PrePab/Issac/Pacer.prefab
Assets/Enemy/PrePab/Spider/Spider.prefab
Assets/Enemy/PrePab/Spider/Tride.prefab
Assets/Enemy/Script/Fly/Footer.cs
Assets/Enemy/Script/Fly/Moter.cs
Assets/Enemy/Script/Issac/Maw.cs
Assets/Enemy/Script/Issac/Pacer.cs
Assets/Enemy/Script/Spider/Spider.cs
Assets/Enemy/Script/Spider/Tride.cs

모든 Enemy에 체력바 UI, 기능 부착 완
위치마다 레이어 바뀌는 스크립트도 부착 완

Enemy 체력바 기능 완

---

Assets/ImageResource/UI/hudstats2.png.meta
Assets/Prefabs/Player/Tear.prefab
Assets/Scenes/02_Game.unity
Assets/Script/ManagerScript/UIManager.cs

플레이어 스탯 UI

---

Assets/Prefabs/Player/Tear.prefab
Assets/Scenes/02_Game.unity
Assets/Script/ManagerScript/UIManager.cs

1.  UI 소수점 2자리만 나오도록 수정
2. Item Storage 위치 변경

UI 소수점 처리.

---

Assets/ImageResource/PlayerAssets/Player/Hit_Sprite.png.meta
Assets/ImageResource/PlayerAssets/Player/Issac_sprite.png.meta
Assets/Prefabs/Player/Tear.prefab
Assets/Scenes/02_Game.unity

아이템을 먹었을 때, 죽었을 때 위치가 바뀌는 현상 조정

플레이어 스프라이트 위치 조정

---

Assets/ImageResource/UI/Banner/Banner.cs
Assets/Item/Active/ActiveInfo.cs
Assets/Item/ItemInfo.cs
Assets/Item/ItemManager.cs
Assets/Item/Trinket/TrinketInfo.cs
Assets/Prefabs/Player/Tear.prefab
Assets/Scenes/02_Game.unity
Assets/Script/ManagerScript/GameManager.cs
Assets/Script/ManagerScript/UIManager.cs
Assets/Script/Player Script/PlayerController.cs

1. Item, Stage Banner 추가
2. 아이템 획득 또는 스테이지 시작시 Banner 출력
3. 배너 출력도중 다른 배너가 출력되어 중첩되지않도록 처리.

Item Banner UI 추가

---

Assets/ImageResource/UI/ItemInfo/ItemExplane.cs
Assets/Prefabs/Player/Player.prefab
Assets/Prefabs/Stage/2Stage/Stage2_BossRoom.prefab
Assets/Prefabs/Stage/2Stage/Stage2_NormalRoom.prefab
Assets/Prefabs/Stage/2Stage/Stage2_StartRoom.prefab
Assets/Prefabs/Stage/3Stage/Stage3_BossRoom.prefab
Assets/Prefabs/Stage/3Stage/Stage3_NormalRoom.prefab
Assets/Prefabs/Stage/3Stage/Stage3_StartRoom.prefab
Assets/Prefabs/Stage/4Stage/Stage4_BossRoom.prefab
Assets/Prefabs/Stage/4Stage/Stage4_NormalRoom.prefab
Assets/Prefabs/Stage/4Stage/Stage4_StartRoom.prefab
Assets/Prefabs/etc/BossHP.prefab
Assets/Prefabs/etc/BossHP.prefab.meta
Assets/Script/ManagerScript/GameManager.cs
Assets/Script/ManagerScript/SoundManager.cs
Assets/Script/Player Script/PlayerController.cs

플레이어 사운드 작업

---

Assets/ImageResource/UI/ItemInfo/ItemExplane.cs
Assets/Item/Coin/Coin.cs
Assets/Item/Coin/coin.prefab
Assets/Item/ItemInfo.cs
Assets/Item/ItemTable.cs
Assets/Item/key/key.cs
Assets/Item/key/key.prefab
Assets/Prefabs/Stage/GoldChest.prefab
Assets/Prefabs/Stage/NormalChest.prefab
Assets/Prefabs/Stage/ShopTable.prefab
Assets/Script/StageScript/Object/ShopTable.cs

1. 열쇠 DROP / PICKUP 사운드 추가
2. 동전 DROP / PICKUP 사운드 추가
3. 아이템정보UI에서 상점테이블 데이터도 받아올수있도록 수정.
4. 아이템 상자 콜라이더 수정

사운드 추가 / 상점 테이블 변경

---

Assets/ImageResource/PlayerAssets/Tear/effect_fart - 복사본.png.meta
Assets/Item/Passive/00_Blood Of The Martyr_OK/BOTM.cs
Assets/Item/Passive/09_Ipecac_OK/Ipecac.cs
Assets/Item/Passive/09_Ipecac_OK/Ipecac.prefab
Assets/Item/Passive/13_Mom's Knife_OK/Mom's Knife.prefab
Assets/Prefabs/Player/Player.prefab
Assets/Prefabs/Player/Tear.prefab
Assets/Script/Player Script/PlayerController.cs
Assets/Script/Player Script/Tear.cs

구토제 아이템 기능 구현

---

Assets/Item/Passive/00_Blood Of The Martyr_OK/BOTM.cs
Assets/Script/ManagerScript/PlayerManager.cs
Assets/Script/Player Script/PlayerController.cs
Assets/Script/Player Script/Tear.cs
Assets/Script/Player Script/TearPoint.cs

PlayerControler, Tear, TearPoint, PlayerManager 작성한 코드 주석 등록

작성한 코드 주석 등록

---

Assets/Enemy/PrePab/Fly/AttackFly.prefab
Assets/Enemy/Script/Boss/BigAttackFly.cs
Assets/Enemy/Script/Boss/Larry/SnakeManager.cs
Assets/Enemy/Script/Enemy_Die.cs
Assets/Enemy/Script/Enemy_Idle.cs
Assets/Enemy/Script/Enemy_Prowl.cs
Assets/Enemy/Script/Enemy_Tracking.cs
Assets/Enemy/Script/Fly/AttackFly.cs
Assets/Enemy/Script/Fly/Footer.cs
Assets/Enemy/Script/Fly/Moter.cs
Assets/Enemy/Script/Issac/Maw.cs
Assets/Enemy/Script/Issac/Pacer.cs
Assets/Enemy/Script/Spider/Spider.cs
Assets/Enemy/Script/Spider/Tride.cs
Assets/Enemy/Script/TEnemy.cs
Assets/Item/Bomb/BombScript/PutBomb.cs
Assets/Script/Player Script/Tear.cs
Assets/Script/StageScript/BossRoom.cs
Assets/Script/StageScript/Room.cs
Assets/Script/StageScript/RoomGenerate.cs

모든 Enemy를 새로 추가한 TEenemy를 상속받고, 오류 안나게 해놓음
몬스터 해당 상태 마다 상태 변환 되게 수정해야함

1115_Enemy_Inherient_Complete

---

Assets/Item/ItemManager.cs
Assets/Scenes/02_Game.unity
Assets/Script/ManagerScript/GameManager.cs
Assets/Script/StageScript/Object/FirePlace.cs
Assets/Script/StageScript/Object/Poop.cs
Assets/Script/StageScript/Object/Rock.cs
Assets/Script/StageScript/Object/Spikes.cs
Assets/Script/StageScript/RoomGenerate.cs

오브젝트  돌 / 똥 / 불 / 가시 
오브젝트 풀링 적용

Object pooling kaffu

---

Assets/Item/Bomb/BombAni/DropBomb/DropBomb.controller
Assets/Item/Bomb/BombPrefabs/DropBomb.prefab
Assets/Item/Bomb/BombScript/DropBomb.cs
Assets/Item/Coin/Coin.cs
Assets/Item/Coin/CoinAnimation/DropCoin.anim
Assets/Item/Coin/CoinAnimation/GetCoin.anim
Assets/Item/Coin/CoinAnimation/GetCoin.controller
Assets/Item/Coin/coin.prefab
Assets/Item/Heart/Heart.cs
Assets/Item/ItemTable.cs
Assets/Item/key/KeyAnimation.controller
Assets/Item/key/key.cs
Assets/Item/key/key.prefab
Assets/Scenes/02_Game.unity
Assets/Script/StageScript/Object/FirePlace.cs
Assets/Script/StageScript/Object/NormalChest.cs
Assets/Script/StageScript/Object/Poop.cs
Assets/Script/StageScript/Room.cs
Assets/Script/StageScript/RoomGenerate.cs

1. 픽업아이템 4종  오브젝트 풀링 적용 완료
2. 일반 상자 픽업아이템 드랍시 오브젝트 풀링 이용
3. 방 클리어 픽업아이템 드랍시 오브젝트 풀링 이용
4. 돌,불 파괴 픽업아이템 드랍시 오브젝트 풀링 이용
- 상점 오브젝트에서 드랍아이템 풀링사용하지않음.
- 액티브/패시브/장신구 아이템은 게임내 1번만 생성하기때문에 풀링사용X

Object pooling 1120 kaffu

---

Assets/Enemy/Animation/Spider/Tride.controller
Assets/Enemy/Animation/Spider/Tride_jump.anim
Assets/Enemy/PrePab/Fly/AttackFly.prefab
Assets/Enemy/PrePab/Fly/Moter.prefab
Assets/Enemy/PrePab/Fly/Pooter.prefab
Assets/Enemy/PrePab/Spider/Tride.prefab
Assets/Enemy/Script/Fly/Moter.cs
Assets/Enemy/Script/Spider/Tride.cs
Assets/Enemy/Script/TEnemy.cs

몬스터 사운드 추가
1. 파리 3종 FLY 사운드 추가
2. 거미 몬스터 TRIDE  착지 사운드 추가

Enemy sound  1121 kaffu

---

Assets/Animation/player/Head/isaacHead.controller
Assets/Item/Bomb/BombScript/PutBomb.cs
Assets/Script/Player Script/PlayerController.cs

PlayerController 스크립트 안 MoveAnim, ShotAnim함수 내부 코드 간략화

발사 애니메이션 코드 간략화

---

Assets/Item/Active/18_Lemon mishap_OK/OopsEffect.cs
Assets/Item/Passive/12_Guardian Angel_OK/Guardian Angel.prefab
Assets/Item/PickUp/Bomb/BombScript/PutBomb.cs
Assets/Scenes/02_Game.unity

1. SOy Milk + Dr.Fetus 습득 시 폭탄이 벽 뚫고 지나가는 현상 수정
2. Guardian Angel에 rigidbody2D 빠져있던 거 수정

1122 Final

---

Assets/Script/ManagerScript/GameManager.cs
Assets/Script/ManagerScript/UIManager.cs

1. 게임시작시 / 방 생성할떄 부자연스러운 로딩실행 수정 및 로딩시간 변경
2. Pause UI  ON OFF > 게임오버 / 로딩  이 켜져있지않을때만 가능

 loading / Pause  동작방식 변경

---

Assets/Animation/player/Head/isaacHead.controller
Assets/Script/ManagerScript/PlayerManager.cs
Assets/Script/Player Script/PlayerController.cs

플레이어 애니메이션 수정

---

Assets/Enemy/PrePab/Boss/Stage4_Gurdy/Gurdy.prefab
Assets/Item/Passive/08_The Wafer_OK/TheWafer.cs
Assets/Item/Trinket/00_Tick_OK/Tick.cs
Assets/Item/Trinket/05_Whip Worm_OK/WhipWorm.cs
Assets/Scenes/02_Game.unity
Assets/Script/ManagerScript/PlayerManager.cs

1. 아이템 눈물 속도 기능 추가, 습득 시 빨라지거나 느려지거나. 최소값 : 2.5
2. Gurdy localScale 1.3 -> 1.05

Dayo 1129 23

---

Assets/Intro_Outro/outro/ImageController.cs
Assets/Intro_Outro/outro/SkipBtn.prefab
Assets/Intro_Outro/outro/VideoController.cs
Assets/Scenes/03_Outro.unity

클리어 경험 유무에 따른 스킵 버튼 생성
